#!/usr/bin/env python3
"""Deterministic micro-codegen for case-0006.

Exists so that "a rename at the generated definition does not survive" is a
constructed fact rather than a claim in a comment. `--check` regenerates from
the contract and compares against the committed file: edit the generated
definition without editing the contract and the check fails, which is exactly
the instability the case asserts.

  tools/codegen.py            write source/generated/api-client.ts
  tools/codegen.py --check    verify the committed file is what the contract generates
"""
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "source" / "contracts" / "api.yaml"
TARGET = ROOT / "source" / "generated" / "api-client.ts"


def render() -> str:
    spec = yaml.safe_load(CONTRACT.read_text())
    lines = [
        "// @generated by tools/codegen.py from contracts/api.yaml -- DO NOT EDIT.",
        "export class ApiClient {",
    ]
    for op in spec["operations"]:
        # /invoices/{id} -> /invoices/${id}
        path = op["path"].replace("{", "${")
        lines += [
            f"  {op['id']}(id: string): Promise<string> {{",
            f"    return Promise.resolve(`{op['method']} {path}`);",
            "  }",
        ]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    out = render()
    if "--check" in sys.argv:
        have = TARGET.read_text()
        if have == out:
            print("  codegen: generated file matches contracts/api.yaml")
            return 0
        print("  codegen: DRIFT -- the committed generated file is not what the", file=sys.stderr)
        print("  contract generates. Either the contract changed without a", file=sys.stderr)
        print("  regeneration, or someone edited the generated file directly.", file=sys.stderr)
        import difflib

        for line in difflib.unified_diff(
            out.splitlines(), have.splitlines(),
            fromfile="generate(contract)", tofile="committed", lineterm="",
        ):
            print(f"    {line}", file=sys.stderr)
        return 1
    TARGET.write_text(out)
    print(f"  codegen: wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
