#!/usr/bin/env python3
"""Deterministic extractor for the frozen graph of FD-v2-GRAPH.

Reads the authoritative Phase G document and emits docs/tasks/a1-f-v2-graph.json.
The extract is not an editable registry: `--check` regenerates it from the
document and fails if the committed JSON differs by one byte, so a drafter
cannot relax a gate by editing its right-hand side.

The source document is pinned by blob, not by path alone. A path can be
rewritten in place; a blob cannot.

Usage:
    python3 tools/a1_v2_extract_graph.py --write     # regenerate the artifact
    python3 tools/a1_v2_extract_graph.py --check     # verify committed == derived
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "docs/tasks/a1-f-v2-phase-g.md"
OUT = REPO / "docs/tasks/a1-f-v2-graph.json"

# Phase G as merged in PR #128. Recorded so the extractor notices if the
# authority it claims to derive from has moved underneath it.
PINNED_BLOB = "450380ff0d1f8ec08f783968f08bc6b3942f44a5"

MESSAGE_KINDS = [
    "WorkOrder", "CoderReport", "CandidateReceipt", "ReviewRequest",
    "ReviewerReport", "ReviewVerdict", "CorrectiveDirective", "CampaignFeedItem",
    "HumanAttentionRequest", "HumanCommandRequest", "HumanDecision",
]
TYPED_SUPPORTS = [
    "ProviderExecutionReceipt", "InteractionManifest", "ScopeContract",
    "CampaignRunBinding",
]
META_TARGETS = {"AnyCommittedEnvelope": MESSAGE_KINDS}


def git_blob_sha(data: bytes) -> str:
    return hashlib.sha1(b"blob %d\x00" % len(data) + data).hexdigest()


def extract(source: Path) -> dict:
    raw = source.read_bytes()
    lines = raw.decode("utf-8").split("\n")

    start = next(i for i, l in enumerate(lines)
                 if l.startswith("| # | source semantic kind"))
    edges = []
    for line in lines[start + 2:]:
        if not line.startswith("|"):
            break
        c = [x.strip().strip("`") for x in line.strip("|").split("|")]
        edges.append({"n": int(c[0]), "source": c[1], "target": c[2],
                      "class": c[3], "origin": c[4]})

    # Structural assertions. These are the frozen numbers; if the document ever
    # disagrees with them the extractor stops rather than emitting a quieter graph.
    assert edges, "no registry table found"
    assert [e["n"] for e in edges] == list(range(1, len(edges) + 1)), "row numbers not contiguous"
    cls = collections.Counter(e["class"] for e in edges)
    assert len(edges) == 69, f"expected 69 edges, found {len(edges)}"
    assert cls["Intra"] == 56 and cls["Causal"] == 13, f"class split moved: {dict(cls)}"
    assert len({(e["source"], e["target"], e["class"]) for e in edges}) == 69, "duplicate edge"

    event_kinds = sorted({re.fullmatch(r"CampaignEvent\((\w+)\)", e["source"]).group(1)
                          for e in edges if e["source"].startswith("CampaignEvent(")})
    payload_variants = sorted({e["target"][:-len("Payload")] for e in edges
                               if e["source"].startswith("CampaignEvent(")
                               and e["target"].endswith("Payload")})
    assert len(event_kinds) == 21, f"expected 21 event kinds, found {len(event_kinds)}"
    assert len(payload_variants) == 11, f"expected 11 payload variants, found {len(payload_variants)}"

    expected_payload = {k: (k + "Payload" if k in payload_variants else None)
                        for k in event_kinds}
    bearing = sum(1 for v in expected_payload.values() if v)
    assert bearing == 11 and len(expected_payload) - bearing == 10, "presence map is not 11/10"

    typed = (set(MESSAGE_KINDS) | set(TYPED_SUPPORTS)
             | {p + "Payload" for p in payload_variants}
             | {f"CampaignEvent({k})" for k in event_kinds})
    nodes = set()
    for e in edges:
        nodes |= {e["source"], e["target"]}
    terminal = sorted(nodes - typed - set(META_TARGETS))
    assert len(typed) == 47, f"expected 47 typed nodes, found {len(typed)}"
    assert len(terminal) == 20, f"expected 20 terminal kinds, found {len(terminal)}"
    assert not (set(META_TARGETS) & {e["source"] for e in edges}), \
        "a meta-target appears as an edge SOURCE; it is a target-position union only"

    return {
        "_comment": ("Frozen graph of FD-v2-GRAPH. GENERATED by "
                     "tools/a1_v2_extract_graph.py from the Phase G document; "
                     "do not hand-edit. Verify with --check."),
        "source_document": str(SOURCE.relative_to(REPO)),
        "source_blob": git_blob_sha(raw),
        "pinned_blob": PINNED_BLOB,
        "status": "APPROVED / CLOSED",
        "message_kinds": MESSAGE_KINDS,
        "typed_supports": TYPED_SUPPORTS,
        "event_kinds": event_kinds,
        "payload_variants": payload_variants,
        "expected_payload": expected_payload,
        "meta_targets": META_TARGETS,
        "terminal_kinds": terminal,
        "edges": edges,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--source", default=str(SOURCE))
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()
    if not (args.write or args.check):
        ap.error("choose --write or --check")

    derived = extract(Path(args.source))
    text = json.dumps(derived, indent=2) + "\n"

    if args.write:
        Path(args.out).write_text(text)
        print(f"wrote {args.out}: {len(derived['edges'])} edges, "
              f"{len(derived['event_kinds'])} event kinds")
        if derived["source_blob"] != PINNED_BLOB:
            print(f"NOTE: source blob {derived['source_blob']} != pinned {PINNED_BLOB}")
        return 0

    committed = Path(args.out).read_text()
    if committed != text:
        print("EXTRACT MISMATCH — the committed graph is not what the Phase G "
              "document derives to.", file=sys.stderr)
        print(f"  source blob : {derived['source_blob']}", file=sys.stderr)
        print(f"  pinned blob : {PINNED_BLOB}", file=sys.stderr)
        return 1
    if derived["source_blob"] != PINNED_BLOB:
        print(f"AUTHORITY MOVED — {SOURCE.name} is blob {derived['source_blob']}, "
              f"pinned {PINNED_BLOB}. Re-pin deliberately or stop.", file=sys.stderr)
        return 1
    print(f"extract OK: committed graph == derived, source blob {PINNED_BLOB}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
