#!/usr/bin/env python3
"""Deterministic extractor for Envelope v2 SCHEMA FACTS.

The middle term of the gate's three-way proof. It exists now, while Envelope v2
has drafted no schema, precisely so that the gate's trust model is fixed before
there is anything to be tempted about: when the field set lands, the
*implementation* of this extractor changes and the gate's trust model does not.

Without it, `schema-facts.json` is a file whose comment asks to be believed —
and a comment asking to be believed is what the ledger's own `_note` fields were
in E-R0, one floor down.

There is no authoritative v2 schema source yet, so the only honest extraction is
the undeclared form: no event kinds, no presence map, no fields. `--check`
verifies the committed facts are exactly that. It fails if someone hand-fills the
arrays and points `extracted_from` at something that does not exist.

Usage:
    python3 tools/a1_v2_extract_schema.py --write
    python3 tools/a1_v2_extract_schema.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs/tasks/a1-f-v2-schema-facts.json"

# When Envelope v2 drafts its schemas, name the source here (path + blob) and
# replace `extract` below with a real reader. Until then the source is absent,
# and saying so is the extraction.
SCHEMA_SOURCE: str | None = None

NOTES = {
    "_comment": (
        "SCHEMA FACTS. GENERATED by tools/a1_v2_extract_schema.py from the ACTUAL "
        "Envelope v2 schemas. The middle term of the three-way proof: authority "
        "(graph.json) <-> actual schema (this file) <-> declared realization "
        "(the ledger). Do not hand-edit; verify with --check."
    ),
    "_event_kinds_note": (
        "The event-kind set the v2 SCHEMA defines. Step 1 compares it to the "
        "frozen 21. A twenty-second kind, or a dropped one, fails there - event "
        "kind is semantic source identity, so an unnoticed kind is an unnoticed "
        "node."
    ),
    "_payload_presence_note": (
        "Total function over every schema event kind: the concrete payload "
        "variant, or null for a payload-free kind. Step 2 compares it to the "
        "frozen 11-one/10-zero map, which catches a schema growing "
        "event_payload_digest on a payload-free kind EVEN IF no ledger row is "
        "ever written for it."
    ),
    "_artifact_ref_fields_note": (
        "Per-field CAPABILITY, not merely a path list: each entry records which "
        "source kind the field belongs to and the complete set of concrete "
        "target kinds it may carry. Phase G 4.2.6 clause 1 requires a field to "
        "declare the complete set of edges it may realize; a bare path list "
        "cannot express that, and lets two fields swap their targets while every "
        "global triple still appears somewhere."
    ),
}


def extract() -> dict:
    if SCHEMA_SOURCE is None:
        return {
            **NOTES,
            "extracted_from": None,
            "extractor": "tools/a1_v2_extract_schema.py",
            "event_kinds": [],
            "payload_presence": {},
            "structural_commitments": [],
            "artifact_ref_fields": [],
        }
    raise NotImplementedError(
        "A v2 schema source is configured but no reader is implemented. "
        "Implement extraction rather than hand-filling the facts."
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()
    if not (args.write or args.check):
        ap.error("choose --write or --check")

    text = json.dumps(extract(), indent=2) + "\n"
    if args.write:
        Path(args.out).write_text(text)
        print(f"wrote {args.out} (schema source: {SCHEMA_SOURCE or 'none yet'})")
        return 0

    if Path(args.out).read_text() != text:
        print("SCHEMA FACTS MISMATCH — the committed facts are not what the "
              "extractor derives. Facts must come from a schema, not from a "
              "keyboard.", file=sys.stderr)
        return 1
    print(f"schema facts OK (schema source: {SCHEMA_SOURCE or 'none yet — steps 1-3 are OWED'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
